name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Ensure this is the correct Node.js version for your project

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          CI: false  # Prevent CI from failing due to warnings; can be removed if not needed
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your AWS region

      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://mygithubalexa --delete  # Use --delete to remove files not present in the build folder from the S3 bucket

      - name: Invalidate CloudFront Cache (optional)
        if: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID != '' }}  # Add this if you use CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
